### PR TITLE
Update tests to run in a reasonable amount of time

### PR DESCRIPTION
**Pull request by crcollins**
There are a few changes that are included in this PR:
1) Using nosetests to collect all the tests instead of a bash script
2) Annotating longer tests with skip (later on these can be annotated with more specific labels if warranted). After this change the tests now run in ~350 seconds instead of ~13200 seconds. It is possible to include the skipped tests by adding `--no-skip` to the nose call in `run_all_tests.sh`.
3) Added a simple try/except catch for the NN imports failing in tests.
4) Added `requirements-dev.txt` to enumerate the requirements for a development install (sklearn, matplotlib, nose, etc).
5) Added an ENVVAR to set the backend for matplotlib (this may not be needed in the future, but it 
6) Adding all the tests to TravisCI builds

This does not resolve the issues with stochastic tests, so this may cause false positives when running tests later. 

With this change, coverage tests also come for free, it is just a matter of adding
`--with-coverage --cover-package=dragonfly --cover-erase`
to the nose call. Down the road, this can also be used in conjunction with Coveralls to include that information in the same way that TravisCI is (if it is wanted).

### CODE REVIEW

**Comment by kirthevasank** [comment]
Seems like some of the builds are failing?

**Comment by crcollins** [comment]
Yeah, some of them are stochastic failures. Some are because direct is not installed (on the ones without direct). And then there are some with syntax errors/undefined vars in Python3.

I am still uncertain what the right fix is for the stochastic tests. The direct error is expected, I just forgot to add a check. The syntax error ones though are tests that i guess were written with Python2 and were not setup to run on Python3, so they might take a bit of work.

**Comment by kirthevasank** [comment]
In that case, shall we just drop the stochastic tests?
I mostly wrote them (several years ago) to test that my GP implementation
was working properly, but I am now fairly confident that they are ok.

**Comment by crcollins** [comment]
I added fixes for the Python2/3 issues, and added skipping of the stochastic test (though, it seems there are more that are less common). I added a hack of a solution for the direct import. It does not really affect the tests, but perhaps it is a good enough patch for now. I think at some point that test should be integrated in with the other tests (using unittest instead of its current check).

It appears some changes you just added have broken some things:
https://travis-ci.org/dragonfly/dragonfly/jobs/497877192
I guess you will have a better idea of what the issue is than me.
As a comparison here is the TravisCI results in my fork:
https://travis-ci.org/crcollins/dragonfly/builds/497877176
The one failed build is another stochastic test that needs to be skipped.

**Comment by kirthevasank** [comment]
Ok, I am going to merge this now. I think the failing tests are due to some changes to the multi-objective optimiser class I made. Will push some fixes shortly.

**Pull request merged**
