### PR TITLE
Skip evaluation errors

### PR DESCRIPTION
**Pull request by h-rummukainen**
These are minimal fixes to handle errors in the objective function evaluation, using the EVAL_ERROR_CODE constant defined in exd_utils.py.  With these fixes, using a randomly failing objective appears to work reasonably well, provided that the acquisition optimization is random (i.e. Thompson sampling, or multiobjective optimization by MOORS).

### CODE REVIEW

**Comment by kirthevasank** [comment]
Hi, thanks for this PR. Do you have any documented instances where this caused an interruption or bug when the algorithm was executed?

**Comment by h-rummukainen** [comment]
I added a variant of the existing synthetic multiobjective Hartmann function that can be used to test evaluation failures.  Without my patches, trying to optimize this new test function makes dragonfly itself fail immediately.

**Comment by kirthevasank** [comment]
I have merged the changes in your first commit but chose not to include the modified examples.

**Comment by h-rummukainen** [comment]
Thank you!

**Pull request closed without merging**
