### PR TITLE
Add rough accessibility to set number of workers

### PR DESCRIPTION
**Pull request by crcollins**
This is just a quick fix for now to expose the number of workers in the in code API. I guess the proper fix would be to use the options to set this.

### CODE REVIEW

**Comment by kirthevasank** [comment]
I am actually working on a fix for this which has rehashed things a fair amount. Expect an update in a day or two.

**Comment by crcollins** [comment]
Okay, sounds good.

**Comment by kirthevasank** [comment]
Check out the latest commit.

**Comment by crcollins** [comment]
Looks like that replaces the need for this. So closing the PR.

**Pull request closed without merging**
